"use client";
import { ChangeEvent, ClipboardEvent, DragEvent, PointerEvent as ReactPointerEvent, useEffect, useMemo, useRef, useState } from "react";
type TextBlock = { text: string; x: number; y: number };
type Card = { text: string; image?: string; layout: "bottom" | "top" | "center"; imageScale?: number; imageX?: number; imageY?: number; textX?: number; textY?: number; extraTexts?: TextBlock[] };
const sourceSample = `이 책에서 가장 많이 반복되는 표현이자, 반드시 쓰지 말아야 한다고 정의하는 표현이 있다. 될 대로 되라지! 조금 더 일상적으로 풀어본다면 '어떻게든 되겠지' 마인드가 아닐까 싶다. 중요한 순간들에 있어서는 어떤 결과가 나오든 나와는 상관없다는 무책임한 의미가 될 수도 있다. 특히 일에서 마주치는 크고 작은 문제들에 어떻게 대처하는가에 따라 성과와 평판이 좌우되기에 결정하는 습관은 더욱 중요해진다. 그렇다면 '될 대로 되라지'라는 마인드의 반대는 기준을 갖고 결정하는 마인드이다. 무언가를 결정한다는 건 그에 따른 리스크를 감내하겠다는 의지이며, 내 결정이 틀렸더라도 이 길을 헤쳐가겠다는 다짐이다. 결정보다 중요한 것은 그 결정을 옳게 만드는 일이다. 과거에 내린 결정을 후회하는 데 시간과 에너지를 쏟지 말자.`;
const focusSample = `중요한 순간에 '어떻게든 되겠지'라는 태도는 어떤 결과가 나오든 나와는 상관없다는 무책임한 의미가 될 수도 있다. 결정의 반대편에는 기준 없이 흘러가는 태도가 있다. 무언가를 결정한다는 건 그에 따른 리스크를 감내하겠다는 의지다. 내 결정이 틀렸더라도 이 길을 헤쳐가겠다는 다짐이기도 하다. 결정보다 중요한 것은 그 결정을 옳게 만드는 일이다.`;
function createCards(title: string, focus: string, previous: Card[]): Card[] {
  const sentences = focus.split(/(?<=[.!?]|다\.)\s+/).map((s) => s.trim()).filter(Boolean);
  const bodyCards = sentences.slice(0, 6).map((text, index) => ({ ...previous[index + 1], text: text.length > 78 ? `${text.slice(0, 77)}…` : text, layout: previous[index + 1]?.layout || (index % 3 === 0 ? "bottom" : index % 3 === 1 ? "top" : "center") as Card["layout"] }));
  return [{ ...previous[0], text: title, layout: previous[0]?.layout || "bottom" }, ...bodyCards];
}
export default function Home() {
  const [title, setTitle] = useState("결정이 어렵다면 지켜야 할 태도"); const [source, setSource] = useState(sourceSample); const [focus, setFocus] = useState(focusSample);
  const [cards, setCards] = useState<Card[]>(() => createCards("결정이 어렵다면 지켜야 할 태도", focusSample, [])); const [active, setActive] = useState(0); const [activeText, setActiveText] = useState(0); const [editMode, setEditMode] = useState<"image" | "text">("image"); const [pasteMessage, setPasteMessage] = useState("영역을 클릭하고 ⌘V"); const current = cards[active];
  useEffect(() => () => cards.forEach((c) => c.image?.startsWith("blob:") && URL.revokeObjectURL(c.image)), []);
  function generate() { setCards((old) => createCards(title, focus, old)); setActive(0); }
  function placeImages(files: File[]) { const images = files.filter((file) => file.type.startsWith("image/")); if (!images.length) { setPasteMessage("이미지를 찾지 못했어요"); return; } setCards((old) => { const next = [...old]; let cursor = next.findIndex((card) => !card.image); if (cursor < 0) cursor = active; images.forEach((file) => { if (cursor >= next.length) return; next[cursor] = { ...next[cursor], image: URL.createObjectURL(file) }; cursor++; }); return next; }); setPasteMessage(`${images.length}장 추가됨`); }
  function addPhotos(event: ChangeEvent<HTMLInputElement>) { placeImages(Array.from(event.target.files || [])); }
  function pastePhotos(event: ClipboardEvent<HTMLDivElement>) { const files = Array.from(event.clipboardData.items).filter((item) => item.kind === "file" && item.type.startsWith("image/")).map((item) => item.getAsFile()).filter((file): file is File => Boolean(file)); if (files.length) { event.preventDefault(); placeImages(files); } else setPasteMessage("이미지를 복사하거나 캡처한 뒤 붙여넣어 주세요"); }
  function dropPhotos(event: DragEvent<HTMLDivElement>) { event.preventDefault(); placeImages(Array.from(event.dataTransfer.files)); }
  function updateCard(patch: Partial<Card>) { setCards((old) => old.map((c, i) => i === active ? { ...c, ...patch } : c)); }
  function updateText(value: string) { if (activeText === 0) updateCard({text:value}); else { const extra=[...(current.extraTexts||[])]; extra[activeText-1]={...extra[activeText-1],text:value}; updateCard({extraTexts:extra}); } }
  function moveText(x:number,y:number) { if(activeText===0) updateCard({textX:x,textY:y}); else { const extra=[...(current.extraTexts||[])]; extra[activeText-1]={...extra[activeText-1],x,y}; updateCard({extraTexts:extra}); } }
  function addText(){const extra=[...(current.extraTexts||[]),{text:"새 문구를 입력하세요",x:540,y:360+(current.extraTexts?.length||0)*170}];updateCard({extraTexts:extra});setActiveText(extra.length);setEditMode("text");}
  function removeText(){if(activeText===0)return;const extra=[...(current.extraTexts||[])];extra.splice(activeText-1,1);updateCard({extraTexts:extra});setActiveText(0);}
  async function saveCard(index = active) {
    const canvas = document.createElement("canvas"); await renderCard(canvas, cards[index], index);
    const link = document.createElement("a"); link.download = `cardletter-${index + 1}.png`; link.href = canvas.toDataURL("image/png"); link.click();
  }
  async function saveAll() { for (let i = 0; i < cards.length; i++) { await saveCard(i); await new Promise((r) => setTimeout(r, 180)); } }
  const photoCount = useMemo(() => cards.filter((c) => c.image).length, [cards]);
  return <main className="app-shell"><header><div className="brand"><span>CL</span><b>CARDLETTER</b><small>블로그에서 골라 만드는 카드뉴스</small></div><button className="save-all" onClick={saveAll}>전체 PNG 저장</button></header>
    <div className="workflow"><span className="done">1 원문 입력</span><i>→</i><span className="done">2 파트 선택</span><i>→</i><span>3 사진·문구 편집</span></div>
    <section className="workspace"><aside className="input-column"><div className="section-head"><span>01</span><div><h2>블로그 글</h2><p>전체 글을 붙여 넣고, 카드로 만들 부분만 골라주세요.</p></div></div>
      <label>카드뉴스 제목<input value={title} onChange={(e) => setTitle(e.target.value)} /></label><label>블로그 원문 <em>{source.length.toLocaleString()}자</em><textarea className="source" value={source} onChange={(e) => setSource(e.target.value)} /></label>
      <div className="focus-block"><label>카드로 만들 파트 <em>{focus.length}자</em><textarea value={focus} onChange={(e) => setFocus(e.target.value)} /></label><p>💡 원문 중 한 가지 메시지가 이어지는 300~700자를 붙여 넣으면 좋아요.</p></div><button className="primary" onClick={generate}>선택한 파트로 카드 구성하기 <b>→</b></button></aside>
      <section className="canvas-column"><div className="section-head"><span>02</span><div><h2>사진과 문구</h2><p>사진을 순서대로 넣고, 각 장의 문구를 다듬으세요.</p></div><label className="upload">사진 추가<input type="file" accept="image/*" multiple onChange={addPhotos}/></label></div>
        <div tabIndex={0} onPaste={pastePhotos} onDragOver={(event) => event.preventDefault()} onDrop={dropPhotos} style={{border:"1px dashed #8d877d",background:"#f7f4ed",padding:"13px 16px",marginBottom:20,display:"flex",alignItems:"center",justifyContent:"space-between",gap:12,outline:"none"}} aria-label="복사한 이미지 또는 캡처 붙여넣기"><span style={{fontSize:12,fontWeight:800}}>📋 복사한 사진·화면 캡처 붙여넣기</span><small style={{fontSize:11,color:"#777"}}>{pasteMessage}</small></div>
        <div className="editor-grid"><div className="stage"><CardCanvas card={current} index={active} mode={editMode} activeText={activeText} onChange={updateCard} onMoveText={moveText}/></div>
          <div className="controls"><div className="segmented" style={{margin:"0 0 12px",flexWrap:"wrap"}}><button className={activeText===0?"on":""} onClick={()=>setActiveText(0)}>문구 1</button>{(current.extraTexts||[]).map((_,i)=><button key={i} className={activeText===i+1?"on":""} onClick={()=>setActiveText(i+1)}>문구 {i+2}</button>)}<button onClick={addText}>＋ 텍스트 추가</button></div><label>선택한 문구<textarea value={activeText===0?current.text:current.extraTexts?.[activeText-1]?.text||""} onChange={(e) => updateText(e.target.value)}/></label>{activeText>0&&<button className="single-save" style={{marginBottom:10,color:"#a23528"}} onClick={removeText}>선택 문구 삭제</button>}
            <div className="control-row"><div><span>드래그로 조정</span><div className="segmented"><button className={editMode === "image" ? "on" : ""} onClick={() => setEditMode("image")}>사진 이동</button><button className={editMode === "text" ? "on" : ""} onClick={() => setEditMode("text")}>문구 이동</button></div></div></div>
            <label>사진 크기 <em style={{float:"right",fontStyle:"normal",fontWeight:400}}>{Math.round((current.imageScale || 1) * 100)}%</em><input type="range" min="1" max="2.5" step="0.05" value={current.imageScale || 1} onChange={(e) => updateCard({imageScale:Number(e.target.value)})}/></label>
            <button className="single-save" style={{marginBottom:8}} onClick={() => updateCard({imageScale:1,imageX:0,imageY:0,textX:undefined,textY:undefined})}>위치·크기 초기화</button>
            <button className="single-save" onClick={() => saveCard()}>현재 카드 PNG 저장 ↓</button><p className="photo-status">사진 {photoCount}/{cards.length}장 · 업로드한 순서대로 카드에 배치됩니다.</p></div></div>
        <div className="filmstrip">{cards.map((c, i) => <button key={i} className={active === i ? "active" : ""} onClick={() => {setActive(i);setActiveText(0)}}><span style={c.image ? {backgroundImage:`url(${c.image})`} : undefined}>{!c.image && "+"}</span><b>{i + 1}</b></button>)}</div></section></section></main>;
}
function CardCanvas({ card, index, mode, activeText, onChange, onMoveText }: { card: Card; index: number; mode: "image" | "text"; activeText:number; onChange: (patch: Partial<Card>) => void; onMoveText:(x:number,y:number)=>void }) { const ref = useRef<HTMLCanvasElement>(null); const drag = useRef<{x:number;y:number;imageX:number;imageY:number;textX:number;textY:number}|null>(null); useEffect(() => { if (ref.current) renderCard(ref.current, card, index); }, [card, index]); function point(event: ReactPointerEvent<HTMLCanvasElement>) { const rect = event.currentTarget.getBoundingClientRect(); return {x:(event.clientX-rect.left)*1080/rect.width,y:(event.clientY-rect.top)*1350/rect.height}; } function down(event:ReactPointerEvent<HTMLCanvasElement>){event.currentTarget.setPointerCapture(event.pointerId);const p=point(event);const d=activeText===0?defaultTextPosition(card,index):(card.extraTexts?.[activeText-1]||{x:540,y:675});drag.current={...p,imageX:card.imageX||0,imageY:card.imageY||0,textX:activeText===0?(card.textX??d.x):d.x,textY:activeText===0?(card.textY??d.y):d.y};} function move(event:ReactPointerEvent<HTMLCanvasElement>){if(!drag.current)return;const p=point(event);const dx=p.x-drag.current.x,dy=p.y-drag.current.y;if(mode==="image")onChange({imageX:drag.current.imageX+dx,imageY:drag.current.imageY+dy});else onMoveText(drag.current.textX+dx,drag.current.textY+dy);} function up(){drag.current=null;} return <canvas ref={ref} width={1080} height={1350} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} style={{width:"min(100%, 430px)",height:"auto",display:"block",boxShadow:"0 18px 38px #28251d32",cursor:mode==="image"?"grab":"move",touchAction:"none"}} aria-label={`${index + 1}번째 카드 미리보기`}/>; }
async function renderCard(canvas: HTMLCanvasElement, card: Card, index: number) {
  canvas.width = 1080; canvas.height = 1350; const ctx = canvas.getContext("2d"); if (!ctx) return; ctx.clearRect(0, 0, 1080, 1350); ctx.fillStyle = "#d2cec6"; ctx.fillRect(0, 0, 1080, 1350);
  if (card.image) { const img = new Image(); img.src = card.image; try { await img.decode(); const scale = Math.max(1080 / img.width, 1350 / img.height) * (card.imageScale || 1); const w = img.width * scale, h = img.height * scale; ctx.drawImage(img, (1080 - w) / 2 + (card.imageX || 0), (1350 - h) / 2 + (card.imageY || 0), w, h); } catch {} }
  else { ctx.fillStyle = "#706c65"; ctx.textAlign = "center"; ctx.font = "700 46px Arial"; ctx.fillText("사진을 추가하세요", 540, 610); ctx.font = "400 30px Arial"; ctx.fillText("권장 1080 × 1350", 540, 665); ctx.textAlign = "left"; }
  if (index === 0) { const grad = ctx.createLinearGradient(0, 590, 0, 1350); grad.addColorStop(0, "transparent"); grad.addColorStop(1, "rgba(0,0,0,.86)"); ctx.fillStyle = grad; ctx.fillRect(0, 0, 1080, 1350); const lines = wrap(ctx, card.text, 790, "700 66px Arial"); const p=defaultTextPosition(card,index); const centerX=card.textX??p.x,centerY=card.textY??p.y; ctx.fillStyle = "white"; ctx.font = "700 66px Arial"; const blockH=lines.length*86; const left=Math.max(40,Math.min(250,centerX-395)); const firstBaseline=centerY-blockH/2+66; lines.forEach((line, i) => ctx.fillText(line, left, firstBaseline + i * 86)); (card.extraTexts||[]).forEach((block)=>drawTextBox(ctx,block.text,block.x,block.y)); return; }
  const p=defaultTextPosition(card,index); drawTextBox(ctx,card.text,card.textX??p.x,card.textY??p.y); (card.extraTexts||[]).forEach((block)=>drawTextBox(ctx,block.text,block.x,block.y));
}
function drawTextBox(ctx:CanvasRenderingContext2D,text:string,centerX:number,centerY:number){const font="700 38px Arial",lineHeight=54,padX=38,padY=30;const lines=wrap(ctx,text,760,font);ctx.font=font;const widest=Math.max(...lines.map((line)=>ctx.measureText(line).width));const boxW=Math.min(836,Math.max(360,Math.ceil(widest+padX*2))),boxH=lines.length*lineHeight+padY*2;const x=Math.max(18,Math.min(1080-boxW-18,centerX-boxW/2)),y=Math.max(18,Math.min(1350-boxH-18,centerY-boxH/2));ctx.fillStyle="white";ctx.fillRect(x,y,boxW,boxH);ctx.strokeStyle="#111";ctx.lineWidth=3;ctx.strokeRect(x,y,boxW,boxH);ctx.fillStyle="#111";ctx.textBaseline="middle";lines.forEach((line,i)=>ctx.fillText(line,x+padX,y+padY+lineHeight/2+i*lineHeight));ctx.textBaseline="alphabetic";}
function defaultTextPosition(card:Card,index:number){if(index===0)return{x:540,y:1050};if(card.layout==="top")return{x:470,y:190};if(card.layout==="center")return{x:540,y:675};return{x:470,y:1135};}
function wrap(ctx: CanvasRenderingContext2D, text: string, maxWidth: number, font: string) { ctx.font = font; const words = text.split(" "); const lines: string[] = []; let line = ""; for (const word of words) { const test = line ? `${line} ${word}` : word; if (ctx.measureText(test).width > maxWidth && line) { lines.push(line); line = word; } else line = test; } if (line) lines.push(line); return lines.slice(0, 7); }
