"use client";
import { ChangeEvent, DragEvent, PointerEvent as ReactPointerEvent, useEffect, useMemo, useRef, useState } from "react";
type TextBlock = { text: string; x: number; y: number };
type Card = { text: string; image?: string; layout: "bottom" | "top" | "center"; imageScale?: number; imageX?: number; imageY?: number; textX?: number; textY?: number; extraTexts?: TextBlock[] };
function createCards(title: string, focus: string, previous: Card[]): Card[] {
  const sentences = focus.split(/(?<=[.!?]|다\.)\s+|\n+/).map((s) => s.trim()).filter(Boolean);
  const coverText = title.trim() || sentences.shift() || "";
  const bodyCards = sentences.map((text, index) => ({ ...previous[index + 1], text, layout: previous[index + 1]?.layout || (index % 3 === 0 ? "bottom" : index % 3 === 1 ? "top" : "center") as Card["layout"] }));
  return [{ ...previous[0], text: coverText, layout: previous[0]?.layout || "bottom" }, ...bodyCards];
}
export default function Home() {
  const [title, setTitle] = useState(""); const [focus, setFocus] = useState("");
  const [cards, setCards] = useState<Card[]>(() => createCards("", "", [])); const [active, setActive] = useState(0); const [activeText, setActiveText] = useState(0); const [editMode, setEditMode] = useState<"image" | "text">("image"); const [pasteMessage, setPasteMessage] = useState("영역을 클릭하고 ⌘V"); const current = cards[active];
  const draggedPage = useRef<number | null>(null);
  const [dropPreview,setDropPreview]=useState<{index:number;side:"before"|"after"}|null>(null);
  useEffect(() => () => cards.forEach((c) => c.image?.startsWith("blob:") && URL.revokeObjectURL(c.image)), []);
  useEffect(() => { function pasteAnywhere(event:globalThis.ClipboardEvent){const files=Array.from(event.clipboardData?.items||[]).filter((item)=>item.kind==="file"&&item.type.startsWith("image/")).map((item)=>item.getAsFile()).filter((file):file is File=>Boolean(file));if(files.length){event.preventDefault();placeImages(files);}}window.addEventListener("paste",pasteAnywhere);return()=>window.removeEventListener("paste",pasteAnywhere);},[active,cards.length]);
  function generate() { setCards((old) => createCards(title, focus, old)); setActive(0); }
  function placeImages(files: File[]) { const images = files.filter((file) => file.type.startsWith("image/")); if (!images.length) { setPasteMessage("이미지를 찾지 못했어요"); return; } const selectedPage=active;const placeable=images.slice(0,Math.max(0,cards.length-selectedPage));setCards((old) => { const next = [...old]; placeable.forEach((file,offset) => { const cursor=selectedPage+offset;const previous=next[cursor].image;if(previous?.startsWith("blob:"))URL.revokeObjectURL(previous);next[cursor] = { ...next[cursor], image: URL.createObjectURL(file) }; }); return next; }); setPasteMessage(`${placeable.length}장 · ${selectedPage+1}페이지부터 추가됨`); }
  function addPhotos(event: ChangeEvent<HTMLInputElement>) { placeImages(Array.from(event.target.files || [])); event.target.value=""; }
  function dropPhotos(event: DragEvent<HTMLDivElement>) { event.preventDefault(); placeImages(Array.from(event.dataTransfer.files)); }
  function updateCard(patch: Partial<Card>) { setCards((old) => old.map((c, i) => i === active ? { ...c, ...patch } : c)); }
  function updateText(value: string) { if (activeText === 0) updateCard({text:value}); else { const extra=[...(current.extraTexts||[])]; extra[activeText-1]={...extra[activeText-1],text:value}; updateCard({extraTexts:extra}); } }
  function moveText(x:number,y:number) { if(activeText===0) updateCard({textX:x,textY:y}); else { const extra=[...(current.extraTexts||[])]; extra[activeText-1]={...extra[activeText-1],x,y}; updateCard({extraTexts:extra}); } }
  function addText(){const extra=[...(current.extraTexts||[]),{text:"새 문구를 입력하세요",x:540,y:360+(current.extraTexts?.length||0)*170}];updateCard({extraTexts:extra});setActiveText(extra.length);setEditMode("text");}
  function removeText(){if(activeText===0)return;const extra=[...(current.extraTexts||[])];extra.splice(activeText-1,1);updateCard({extraTexts:extra});setActiveText(0);}
  function addPage(){const newCard:Card={text:"새 문구를 입력하세요",layout:"bottom",imageScale:1,imageX:0,imageY:0,extraTexts:[]};setCards((old)=>[...old,newCard]);setActive(cards.length);setActiveText(0);setEditMode("text");}
  function removePage(){if(cards.length<=1)return;const removed=cards[active];if(removed.image?.startsWith("blob:"))URL.revokeObjectURL(removed.image);const nextActive=Math.min(active,cards.length-2);setCards((old)=>old.filter((_,index)=>index!==active));setActive(nextActive);setActiveText(0);}
  function reorderPage(from:number,to:number){if(from===to||from<0||to<0||from>=cards.length||to>=cards.length)return;setCards((old)=>{const next=[...old];const [moved]=next.splice(from,1);next.splice(to,0,moved);return next;});setActive((selected)=>selected===from?to:from<selected&&selected<=to?selected-1:to<=selected&&selected<from?selected+1:selected);setActiveText(0);}
  function dropPage(from:number,target:number,side:"before"|"after"){let insertion=target+(side==="after"?1:0);if(from<insertion)insertion-=1;reorderPage(from,Math.max(0,Math.min(cards.length-1,insertion)));setDropPreview(null);}
  async function saveCard(index = active) {
    const canvas = document.createElement("canvas"); await renderCard(canvas, cards[index], index);
    const link = document.createElement("a"); link.download = `cardletter-${index + 1}.png`; link.href = canvas.toDataURL("image/png"); link.click();
  }
  async function saveAll() { for (let i = 0; i < cards.length; i++) { await saveCard(i); await new Promise((r) => setTimeout(r, 180)); } }
  const photoCount = useMemo(() => cards.filter((c) => c.image).length, [cards]);
  return <main className="app-shell"><header><div className="brand"><span>CL</span><b>CARDLETTER</b><small>블로그에서 골라 만드는 카드뉴스</small></div><button className="save-all" onClick={saveAll}>전체 PNG 저장</button></header>
    <div className="workflow"><span className="done">1 제목·본문 입력</span><i>→</i><span className="done">2 카드 만들기</span><i>→</i><span>3 사진·문구 편집</span></div>
    <section className="workspace"><aside className="input-column"><div className="section-head"><span>01</span><div><h2>카드뉴스 내용</h2><p>썸네일 카피와 본문을 입력하면 문장별 카드로 나눠드려요.</p></div></div>
      <label>카드뉴스 제목 <small>(썸네일 카피)</small><input placeholder="1페이지에 들어갈 제목을 입력하세요" value={title} onChange={(e) => setTitle(e.target.value)} /></label>
      <label>본문 <em>{focus.length.toLocaleString()}자</em><textarea className="card-body-source" placeholder="카드뉴스 본문을 입력하세요. 마침표, 물음표, 느낌표 또는 줄바꿈을 기준으로 카드가 나뉩니다." value={focus} onChange={(e) => setFocus(e.target.value)} /></label><p className="sentence-guide">문장 하나가 카드 한 장이 됩니다. 원하는 위치에서 줄을 바꿔 직접 카드를 나눌 수도 있어요.</p><button className="primary" onClick={generate}>카드 만들기 <b>→</b></button></aside>
      <section className="canvas-column"><div className="section-head"><span>02</span><div><h2>사진과 문구</h2><p>선택한 페이지부터 사진을 넣고, 각 장의 문구를 다듬으세요.</p></div><label className="upload">사진 추가<input type="file" accept="image/*" multiple onChange={addPhotos}/></label></div>
        <div className="paste-zone" onDragOver={(event) => event.preventDefault()} onDrop={dropPhotos} aria-label="복사한 이미지 또는 캡처 붙여넣기"><div className="paste-icon">⌘V</div><div><strong>사진을 복사한 뒤 바로 붙여넣으세요</strong><p>이 영역을 먼저 클릭할 필요 없이, 제작기 화면 어디에서든 <b>⌘V</b></p><small>화면 캡처도 같은 방법으로 추가할 수 있어요 · 파일을 이곳에 끌어놓아도 됩니다.</small></div><em>{pasteMessage}</em></div>
        <div className="editor-grid"><div className="stage"><CardCanvas card={current} index={active} mode={editMode} activeText={activeText} onChange={updateCard} onMoveText={moveText}/></div>
          <div className="controls"><div className="segmented" style={{margin:"0 0 12px",flexWrap:"wrap"}}><button className={activeText===0?"on":""} onClick={()=>setActiveText(0)}>문구 1</button>{(current.extraTexts||[]).map((_,i)=><button key={i} className={activeText===i+1?"on":""} onClick={()=>setActiveText(i+1)}>문구 {i+2}</button>)}<button onClick={addText}>＋ 텍스트 추가</button></div><label>선택한 문구<textarea value={activeText===0?current.text:current.extraTexts?.[activeText-1]?.text||""} onChange={(e) => updateText(e.target.value)}/></label>{activeText>0&&<button className="single-save" style={{marginBottom:10,color:"#a23528"}} onClick={removeText}>선택 문구 삭제</button>}
            <div className="control-row"><div><span>드래그로 조정</span><div className="segmented"><button className={editMode === "image" ? "on" : ""} onClick={() => setEditMode("image")}>사진 이동</button><button className={editMode === "text" ? "on" : ""} onClick={() => setEditMode("text")}>문구 이동</button></div></div></div>
            <label>사진 크기 <em style={{float:"right",fontStyle:"normal",fontWeight:400}}>{Math.round((current.imageScale || 1) * 100)}%</em><input type="range" min="1" max="2.5" step="0.05" value={current.imageScale || 1} onChange={(e) => updateCard({imageScale:Number(e.target.value)})}/></label>
            <div className="page-actions single"><button className="danger" onClick={removePage} disabled={cards.length<=1}>현재 페이지 삭제</button></div>
            <button className="single-save" style={{marginBottom:8}} onClick={() => updateCard({imageScale:1,imageX:0,imageY:0,textX:undefined,textY:undefined})}>위치·크기 초기화</button>
            <button className="single-save" onClick={() => saveCard()}>현재 카드 PNG 저장 ↓</button><p className="photo-status">사진 {photoCount}/{cards.length}장 · 선택한 페이지부터 순서대로 배치됩니다.</p></div></div>
        <div className="filmstrip" aria-label="페이지 순서 변경" onDragOver={(event)=>event.preventDefault()} onDrop={(event)=>{event.preventDefault();if(draggedPage.current!==null&&dropPreview){if(dropPreview.index===cards.length)dropPage(draggedPage.current,cards.length-1,"after");else dropPage(draggedPage.current,dropPreview.index,dropPreview.side)}draggedPage.current=null}}>{cards.map((c, i) => <button key={i} draggable className={`${active===i?"active":""} ${dropPreview?.index===i?`drop-${dropPreview.side}`:""}`} title="누른 채 좌우로 끌어 순서 변경" aria-label={`${i+1}페이지 선택 및 순서 변경`} onClick={() => {setActive(i);setActiveText(0)}} onDragStart={(event)=>{draggedPage.current=i;setDropPreview(null);event.currentTarget.classList.add("dragging");event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",String(i))}} onDragOver={(event)=>{event.preventDefault();event.dataTransfer.dropEffect="move";const rect=event.currentTarget.getBoundingClientRect();setDropPreview({index:i,side:event.clientX<rect.left+rect.width/2?"before":"after"})}} onDrop={(event)=>{event.preventDefault();event.stopPropagation();const rect=event.currentTarget.getBoundingClientRect();const side=event.clientX<rect.left+rect.width/2?"before":"after";if(draggedPage.current!==null)dropPage(draggedPage.current,i,side);draggedPage.current=null}} onDragEnd={(event)=>{event.currentTarget.classList.remove("dragging");draggedPage.current=null;setDropPreview(null)}}><span style={c.image ? {backgroundImage:`url(${c.image})`} : undefined}>{!c.image && "+"}</span><b>{i + 1}</b></button>)}<button className={`add-page ${dropPreview?.index===cards.length?"drop-before":""}`} onClick={addPage} onDragOver={(event)=>{event.preventDefault();setDropPreview({index:cards.length,side:"before"})}} onDrop={(event)=>{event.preventDefault();event.stopPropagation();if(draggedPage.current!==null)dropPage(draggedPage.current,cards.length-1,"after");draggedPage.current=null}} aria-label="새 페이지 추가" title="새 페이지 추가"><span>＋</span></button><small>썸네일을 누른 채 끌어서 순서를 바꿀 수 있어요.</small></div></section></section></main>;
}
function CardCanvas({ card, index, mode, activeText, onChange, onMoveText }: { card: Card; index: number; mode: "image" | "text"; activeText:number; onChange: (patch: Partial<Card>) => void; onMoveText:(x:number,y:number)=>void }) { const ref = useRef<HTMLCanvasElement>(null); const drag = useRef<{x:number;y:number;imageX:number;imageY:number;textX:number;textY:number}|null>(null); useEffect(() => { if (ref.current) renderCard(ref.current, card, index); }, [card, index]); function point(event: ReactPointerEvent<HTMLCanvasElement>) { const rect = event.currentTarget.getBoundingClientRect(); return {x:(event.clientX-rect.left)*1080/rect.width,y:(event.clientY-rect.top)*1350/rect.height}; } function down(event:ReactPointerEvent<HTMLCanvasElement>){event.currentTarget.setPointerCapture(event.pointerId);const p=point(event);const d=activeText===0?defaultTextPosition(card,index):(card.extraTexts?.[activeText-1]||{x:540,y:675});drag.current={...p,imageX:card.imageX||0,imageY:card.imageY||0,textX:activeText===0?(card.textX??d.x):d.x,textY:activeText===0?(card.textY??d.y):d.y};} function move(event:ReactPointerEvent<HTMLCanvasElement>){if(!drag.current)return;const p=point(event);const dx=p.x-drag.current.x,dy=p.y-drag.current.y;if(mode==="image")onChange({imageX:drag.current.imageX+dx,imageY:drag.current.imageY+dy});else onMoveText(drag.current.textX+dx,drag.current.textY+dy);} function up(){drag.current=null;} return <canvas ref={ref} width={1080} height={1350} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} style={{width:"min(100%, 430px)",height:"auto",display:"block",boxShadow:"0 18px 38px #28251d32",cursor:mode==="image"?"grab":"move",touchAction:"none"}} aria-label={`${index + 1}번째 카드 미리보기`}/>; }
async function renderCard(canvas: HTMLCanvasElement, card: Card, index: number) {
  canvas.width = 1080; canvas.height = 1350; const ctx = canvas.getContext("2d"); if (!ctx) return; ctx.clearRect(0, 0, 1080, 1350); ctx.fillStyle = "#d2cec6"; ctx.fillRect(0, 0, 1080, 1350);
  if (card.image) { const img = new Image(); img.src = card.image; try { await img.decode(); const scale = Math.max(1080 / img.width, 1350 / img.height) * (card.imageScale || 1); const w = img.width * scale, h = img.height * scale; ctx.drawImage(img, (1080 - w) / 2 + (card.imageX || 0), (1350 - h) / 2 + (card.imageY || 0), w, h); } catch {} }
  else { ctx.fillStyle = "#706c65"; ctx.textAlign = "center"; ctx.font = "700 46px Arial"; ctx.fillText("사진을 추가하세요", 540, 610); ctx.font = "400 30px Arial"; ctx.fillText("권장 1080 × 1350", 540, 665); ctx.textAlign = "left"; }
  if (index === 0) { const grad = ctx.createLinearGradient(0, 590, 0, 1350); grad.addColorStop(0, "transparent"); grad.addColorStop(1, "rgba(0,0,0,.9)"); ctx.fillStyle = grad; ctx.fillRect(0, 0, 1080, 1350); const coverFont="900 84px Arial"; const lines = wrap(ctx, card.text, 880, coverFont); const p=defaultTextPosition(card,index); const centerX=Math.max(440,Math.min(640,card.textX??p.x)),centerY=card.textY??p.y; ctx.fillStyle = "white"; ctx.font = coverFont; ctx.textAlign="center"; ctx.shadowColor="rgba(0,0,0,.42)";ctx.shadowBlur=8;ctx.shadowOffsetX=1;ctx.shadowOffsetY=3; const lineHeight=106,blockH=lines.length*lineHeight; const firstBaseline=centerY-blockH/2+84; lines.forEach((line, i) => ctx.fillText(line, centerX, firstBaseline + i * lineHeight)); ctx.shadowColor="transparent";ctx.shadowBlur=0;ctx.shadowOffsetX=0;ctx.shadowOffsetY=0;ctx.textAlign="left"; (card.extraTexts||[]).forEach((block)=>drawTextBox(ctx,block.text,block.x,block.y)); return; }
  const p=defaultTextPosition(card,index); drawTextBox(ctx,card.text,card.textX??p.x,card.textY??p.y); (card.extraTexts||[]).forEach((block)=>drawTextBox(ctx,block.text,block.x,block.y));
}
function drawTextBox(ctx:CanvasRenderingContext2D,text:string,centerX:number,centerY:number){const font="700 38px Arial",lineHeight=54,padX=38,padY=30;const lines=wrap(ctx,text,760,font);ctx.font=font;const widest=Math.max(...lines.map((line)=>ctx.measureText(line).width));const boxW=Math.min(836,Math.max(360,Math.ceil(widest+padX*2))),boxH=lines.length*lineHeight+padY*2;const x=Math.max(18,Math.min(1080-boxW-18,centerX-boxW/2)),y=Math.max(18,Math.min(1350-boxH-18,centerY-boxH/2));ctx.fillStyle="white";ctx.fillRect(x,y,boxW,boxH);ctx.strokeStyle="#111";ctx.lineWidth=3;ctx.strokeRect(x,y,boxW,boxH);ctx.fillStyle="#111";ctx.textBaseline="middle";lines.forEach((line,i)=>ctx.fillText(line,x+padX,y+padY+lineHeight/2+i*lineHeight));ctx.textBaseline="alphabetic";}
function defaultTextPosition(card:Card,index:number){if(index===0)return{x:540,y:1050};if(card.layout==="top")return{x:470,y:190};if(card.layout==="center")return{x:540,y:675};return{x:470,y:1135};}
function wrap(ctx: CanvasRenderingContext2D, text: string, maxWidth: number, font: string) { ctx.font = font; const lines: string[] = []; const paragraphs=text.replace(/\r\n?/g,"\n").split("\n"); for(const paragraph of paragraphs){if(!paragraph.trim()){lines.push("");continue;}const words=paragraph.trim().split(/\s+/);let line="";for(const word of words){const test=line?`${line} ${word}`:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word;}else line=test;}if(line)lines.push(line);}return lines.length?lines:[""]; }
