"use client";
import { ChangeEvent, PointerEvent as ReactPointerEvent, useEffect, useMemo, useRef, useState } from "react";
import { zipSync } from "fflate";
import "@ibm/plex-sans-kr/css/ibm-plex-sans-kr-default.css";
type TextStyle = "default" | "point";
type TextBlock = { text: string; x: number; y: number; style?: TextStyle; letterSpacing?: number; widthScale?: number };
type Card = { text: string; textStyle?: TextStyle; textLetterSpacing?: number; textWidthScale?: number; image?: string; image2?: string; overlayImage?: string; overlayAspect?: number; overlayWidth?: number; overlayX?: number; overlayY?: number; photoLayout?: "single" | "split"; layout: "bottom" | "top" | "center"; imageScale?: number; imageX?: number; imageY?: number; image2Scale?: number; image2X?: number; image2Y?: number; textX?: number; textY?: number; extraTexts?: TextBlock[] };
function createCards(title: string, focus: string, previous: Card[]): Card[] {
  const paragraphs = focus.replace(/\r\n?/g, "\n").split(/\n[ \t]*\n+/).map((paragraph) => paragraph.trim()).filter(Boolean);
  const coverText = title.trim() || paragraphs.shift() || "";
  const bodyCards = paragraphs.map((text, index) => ({ ...previous[index + 1], text, layout: previous[index + 1]?.layout || (index % 3 === 0 ? "bottom" : index % 3 === 1 ? "top" : "center") as Card["layout"] }));
  return [{ ...previous[0], text: coverText, layout: previous[0]?.layout || "bottom" }, ...bodyCards];
}
function imageFiles(items:DataTransferItemList){return Array.from(items).filter((item)=>item.kind==="file"&&item.type.startsWith("image/")).map((item)=>item.getAsFile()).filter((file):file is File=>Boolean(file));}
export default function Home() {
  const [title, setTitle] = useState(""); const [focus, setFocus] = useState("");
  const [cards, setCards] = useState<Card[]>(() => createCards("", "", [])); const [active, setActive] = useState(0); const [activeText, setActiveText] = useState(0); const [activeImage,setActiveImage]=useState<0|1>(0); const [pasteMessage, setPasteMessage] = useState("Mac ⌘V · Windows Ctrl+V"); const current = cards[active];
  const [zipProgress,setZipProgress]=useState<number|null>(null);
  const draggedPage = useRef<number | null>(null);
  const undoStack = useRef<Card[][]>([]); const previousCards = useRef(cards); const restoringUndo = useRef(false);
  const [dropPreview,setDropPreview]=useState<{index:number;side:"before"|"after"}|null>(null);
  useEffect(()=>{if(restoringUndo.current){restoringUndo.current=false;previousCards.current=cards;return}if(previousCards.current!==cards){undoStack.current.push(previousCards.current);if(undoStack.current.length>100)undoStack.current.shift();previousCards.current=cards}},[cards]);
  useEffect(()=>{function keydown(event:KeyboardEvent){if(!(event.ctrlKey||event.metaKey)||event.key.toLowerCase()!=="z"||event.shiftKey)return;const target=event.target as HTMLElement|null;if(target?.closest(".input-column"))return;const previous=undoStack.current.pop();if(!previous)return;event.preventDefault();restoringUndo.current=true;setCards(previous);setActive((value)=>Math.min(value,previous.length-1));setActiveText(0);setActiveImage(0);setPasteMessage("방금 작업을 되돌렸어요")}window.addEventListener("keydown",keydown);return()=>window.removeEventListener("keydown",keydown)},[]);
  useEffect(() => () => cards.forEach((c) => {if(c.image?.startsWith("blob:"))URL.revokeObjectURL(c.image);if(c.image2?.startsWith("blob:"))URL.revokeObjectURL(c.image2);if(c.overlayImage?.startsWith("blob:"))URL.revokeObjectURL(c.overlayImage)}), []);
  useEffect(() => { function pasteAnywhere(event:globalThis.ClipboardEvent){const files=event.clipboardData?imageFiles(event.clipboardData.items):[];if(files.length){event.preventDefault();placeImages(files);}}window.addEventListener("paste",pasteAnywhere);return()=>window.removeEventListener("paste",pasteAnywhere);},[active,activeImage,cards.length]);
  function generate() { setCards((old) => createCards(title, focus, old)); setActive(0); setActiveImage(0); }
  function placeImages(files: File[]) { const images = files.filter((file) => file.type.startsWith("image/")); if (!images.length) { setPasteMessage("이미지를 찾지 못했어요"); return; } if(activeImage===1&&active>0){const file=images[0];setCards((old)=>old.map((card,index)=>index===active?{...card,photoLayout:"split",image2:URL.createObjectURL(file)}:card));setPasteMessage(`${active+1}페이지 아래 칸에 사진이 추가됨`);return;} const selectedPage=active;const placeable=images.slice(0,Math.max(0,cards.length-selectedPage));setCards((old) => { const next = [...old]; placeable.forEach((file,offset) => { const cursor=selectedPage+offset;next[cursor] = { ...next[cursor], image: URL.createObjectURL(file) }; }); return next; }); setPasteMessage(`${placeable.length}장 · ${selectedPage+1}페이지부터 추가됨`); }
  function addPhotos(event: ChangeEvent<HTMLInputElement>) { placeImages(Array.from(event.target.files || [])); event.target.value=""; }
  function addSlotPhoto(event:ChangeEvent<HTMLInputElement>,slot:0|1){const file=Array.from(event.target.files||[]).find((item)=>item.type.startsWith("image/"));if(file){setCards((old)=>old.map((card,index)=>index===active?slot===0?{...card,image:URL.createObjectURL(file),imageScale:1,imageX:0,imageY:0}:{...card,photoLayout:"split",image2:URL.createObjectURL(file),image2Scale:1,image2X:0,image2Y:0}:card));setActiveImage(slot);setPasteMessage(`${active+1}페이지 ${slot===0?"위":"아래"} 칸에 사진이 추가됨`)}event.target.value="";}
  async function addOverlayImage(event:ChangeEvent<HTMLInputElement>){const file=Array.from(event.target.files||[]).find((item)=>item.type.startsWith("image/"));if(file){const url=URL.createObjectURL(file),image=new Image();image.src=url;try{await image.decode();updateCard({overlayImage:url,overlayAspect:image.width/image.height,overlayWidth:360,overlayX:760,overlayY:1030});setPasteMessage("작은 이미지가 추가됨 · 미리보기에서 바로 끌어 이동하세요")}catch{URL.revokeObjectURL(url)}}event.target.value="";}
  function removeOverlayImage(){updateCard({overlayImage:undefined,overlayAspect:undefined,overlayWidth:undefined,overlayX:undefined,overlayY:undefined});}
  function updateCard(patch: Partial<Card>) { setCards((old) => old.map((c, i) => i === active ? { ...c, ...patch } : c)); }
  function updateText(value: string) { if (activeText === 0) updateCard({text:value}); else { const extra=[...(current.extraTexts||[])]; extra[activeText-1]={...extra[activeText-1],text:value}; updateCard({extraTexts:extra}); } }
  function moveText(textIndex:number,x:number,y:number) { if(textIndex===0) updateCard({textX:x,textY:y}); else { const extra=[...(current.extraTexts||[])]; extra[textIndex-1]={...extra[textIndex-1],x,y}; updateCard({extraTexts:extra}); } }
  function addText(){const extra=[...(current.extraTexts||[]),{text:"새 문구를 입력하세요",x:540,y:360+(current.extraTexts?.length||0)*170}];updateCard({extraTexts:extra});setActiveText(extra.length);}
  function addPointText(){const extra=[...(current.extraTexts||[]),{text:"포인트 문구를 입력하세요",x:540,y:360+(current.extraTexts?.length||0)*170,style:"point" as TextStyle,letterSpacing:-1.5,widthScale:.86}];updateCard({extraTexts:extra});setActiveText(extra.length);}
  function setTextStyle(style:TextStyle){const point=style==="point";if(activeText===0)updateCard({textStyle:style,textLetterSpacing:point?-1.5:0,textWidthScale:point?0.86:1});else{const extra=[...(current.extraTexts||[])];extra[activeText-1]={...extra[activeText-1],style,letterSpacing:point?-1.5:0,widthScale:point?0.86:1};updateCard({extraTexts:extra});}}
  function updatePointTypography(letterSpacing?:number,widthScale?:number){if(activeText===0)updateCard({textLetterSpacing:letterSpacing??current.textLetterSpacing,textWidthScale:widthScale??current.textWidthScale});else{const extra=[...(current.extraTexts||[])],item=extra[activeText-1];extra[activeText-1]={...item,letterSpacing:letterSpacing??item.letterSpacing,widthScale:widthScale??item.widthScale};updateCard({extraTexts:extra});}}
  function removeText(){if(activeText===0)return;const extra=[...(current.extraTexts||[])];extra.splice(activeText-1,1);updateCard({extraTexts:extra});setActiveText(0);}
  function removeSecondPhoto(){updateCard({photoLayout:"single",image2:undefined,image2Scale:1,image2X:0,image2Y:0});setActiveImage(0);}
  function setPhotoLayout(layout:"single"|"split"){if(active===0)return;if(layout==="single"){removeSecondPhoto();return;}updateCard({photoLayout:"split"});setActiveImage(current.image?1:0);setPasteMessage("위·아래 두 칸 레이아웃 · 아래 칸에 사진을 추가하세요");}
  function addPage(){const newCard:Card={text:"새 문구를 입력하세요",layout:"bottom",imageScale:1,imageX:0,imageY:0,extraTexts:[]};setCards((old)=>[...old,newCard]);setActive(cards.length);setActiveText(0);setActiveImage(0);}
  function removePage(){if(cards.length<=1)return;const nextActive=Math.min(active,cards.length-2);setCards((old)=>old.filter((_,index)=>index!==active));setActive(nextActive);setActiveText(0);setActiveImage(0);}
  function reorderPage(from:number,to:number){if(from===to||from<0||to<0||from>=cards.length||to>=cards.length)return;setCards((old)=>{const next=[...old];const [moved]=next.splice(from,1);next.splice(to,0,moved);return next;});setActive((selected)=>selected===from?to:from<selected&&selected<=to?selected-1:to<=selected&&selected<from?selected+1:selected);setActiveText(0);}
  function dropPage(from:number,target:number,side:"before"|"after"){let insertion=target+(side==="after"?1:0);if(from<insertion)insertion-=1;reorderPage(from,Math.max(0,Math.min(cards.length-1,insertion)));setDropPreview(null);}
  async function saveCard(index = active) {
    const canvas = document.createElement("canvas"); await renderCard(canvas, cards[index], index);
    const link = document.createElement("a"); link.download = `cardletter-${index + 1}.png`; link.href = canvas.toDataURL("image/png"); link.click();
  }
  async function saveAll() {if(zipProgress!==null)return;setZipProgress(0);try{const files:Record<string,Uint8Array>={};const digits=Math.max(2,String(cards.length).length);for(let i=0;i<cards.length;i++){const canvas=document.createElement("canvas");await renderCard(canvas,cards[i],i);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob((value)=>value?resolve(value):reject(new Error("PNG 생성 실패")),"image/png"));files[`cardletter-${String(i+1).padStart(digits,"0")}.png`]=new Uint8Array(await blob.arrayBuffer());setZipProgress(i+1);}const zipBlob=new Blob([zipSync(files,{level:6})],{type:"application/zip"});const url=URL.createObjectURL(zipBlob);const link=document.createElement("a");const safeName=(title.trim()||"cardletter").replace(/[\\/:*?"<>|]/g,"-");link.download=`${safeName}.zip`;link.href=url;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}finally{setZipProgress(null);}}
  const photoCount = useMemo(() => cards.reduce((count,c)=>count+(c.image?1:0)+(c.image2?1:0)+(c.overlayImage?1:0),0), [cards]);
  return <main className="app-shell"><header><div className="brand"><span>JL</span><b>Jlife Cardnews Maker</b></div><button className="save-all" onClick={saveAll} disabled={zipProgress!==null}>{zipProgress===null?"전체 PNG ZIP 저장":`압축 중 ${zipProgress}/${cards.length}`}</button></header>
    <div className="workflow"><span className="done">1 제목·본문 입력</span><i>→</i><span className="done">2 카드 만들기</span><i>→</i><span>3 사진·문구 편집</span></div>
    <section className="workspace"><aside className="input-column"><div className="section-head"><span>01</span><div><h2>카드뉴스 내용</h2><p>썸네일 카피와 본문을 입력하면 문단별 카드로 나눠드려요.</p></div></div>
      <label>카드뉴스 제목 <small>(썸네일 카피)</small><input placeholder="1페이지에 들어갈 제목을 입력하세요" value={title} onChange={(e) => setTitle(e.target.value)} /></label>
      <label>본문 <em>{focus.length.toLocaleString()}자</em><textarea className="card-body-source" placeholder="카드뉴스 본문을 입력하세요. 빈 줄로 문단을 나누면 문단마다 새 카드가 만들어집니다." value={focus} onChange={(e) => setFocus(e.target.value)} /></label><p className="sentence-guide">문단 하나가 카드 한 장이 됩니다. 한 번의 줄바꿈은 같은 카드 안에 유지되고, 빈 줄(Enter 두 번)에서 새 카드가 시작됩니다.</p><button className="primary" onClick={generate}>카드 만들기 <b>→</b></button></aside>
      <section className="canvas-column"><div className="section-head"><span>02</span><div><h2>사진과 문구</h2><p>선택한 페이지부터 사진을 넣고, 각 장의 문구를 다듬으세요.</p></div><label className="upload">사진 추가<input type="file" accept="image/*" multiple onChange={addPhotos}/></label></div>
        <div className="editor-grid"><div className="stage" tabIndex={0} onClick={(event)=>event.currentTarget.focus()} onFocus={()=>setPasteMessage(`사진 ${activeImage+1} 선택됨 · 붙여넣기 키를 누르세요`)} onPaste={(event)=>{const files=imageFiles(event.clipboardData.items);if(files.length){event.preventDefault();event.stopPropagation();placeImages(files)}else setPasteMessage("클립보드에서 사진을 찾지 못했어요")}} aria-label="사진을 붙여넣을 카드 미리보기"><CardCanvas card={current} index={active} activeImage={activeImage} onSelectImage={setActiveImage} onSelectText={setActiveText} onChange={updateCard} onMoveText={moveText}/></div>
          <div className="controls"><div className="segmented" style={{margin:"0 0 12px",flexWrap:"wrap"}}><button className={activeText===0?"on":""} onClick={()=>setActiveText(0)}>문구 1</button>{(current.extraTexts||[]).map((item,i)=><button key={i} className={activeText===i+1?"on":""} onClick={()=>setActiveText(i+1)}>{item.style==="point"?"포인트":"문구"} {i+2}</button>)}<button onClick={addText}>＋ 텍스트</button><button onClick={addPointText} style={{background:"#feb249"}}>＋ 포인트</button></div><label>선택한 문구<textarea value={activeText===0?current.text:current.extraTexts?.[activeText-1]?.text||""} onChange={(e) => updateText(e.target.value)} style={{width:"min(100%, 504px)",padding:"18px 23px",whiteSpace:"pre-wrap",wordBreak:"keep-all",overflowWrap:"normal",letterSpacing:(activeText===0?current.textLetterSpacing:current.extraTexts?.[activeText-1]?.letterSpacing)??0,fontFamily:(activeText===0?current.textStyle:current.extraTexts?.[activeText-1]?.style)==="point"?"IBM Plex Sans KR, sans-serif":"Pretendard, sans-serif",fontWeight:(activeText===0?current.textStyle:current.extraTexts?.[activeText-1]?.style)==="point"?400:active===0&&activeText===0?800:600,fontSize:active===0&&activeText===0?43.5:22.8,lineHeight:active===0&&activeText===0?1.262:1.421,background:(activeText===0?current.textStyle:current.extraTexts?.[activeText-1]?.style)==="point"?"#feb249":"white"}}/></label><div className="photo-slots"><span>문구 스타일</span><div className="segmented"><button className={(activeText===0?current.textStyle:current.extraTexts?.[activeText-1]?.style)!=="point"?"on":""} onClick={()=>setTextStyle("default")}>기본</button><button className={(activeText===0?current.textStyle:current.extraTexts?.[activeText-1]?.style)==="point"?"on":""} onClick={()=>setTextStyle("point")} style={{background:(activeText===0?current.textStyle:current.extraTexts?.[activeText-1]?.style)==="point"?"#feb249":"white",color:"#181816"}}>포인트</button></div></div>{(activeText===0?current.textStyle:current.extraTexts?.[activeText-1]?.style)==="point"&&<div className="point-typography"><label>글자 폭 <em>{Math.round(((activeText===0?current.textWidthScale:current.extraTexts?.[activeText-1]?.widthScale)??0.86)*100)}%</em><input type="range" min=".7" max="1.05" step=".01" value={(activeText===0?current.textWidthScale:current.extraTexts?.[activeText-1]?.widthScale)??0.86} onChange={(e)=>updatePointTypography(undefined,Number(e.target.value))}/></label><label>자간 <em>{((activeText===0?current.textLetterSpacing:current.extraTexts?.[activeText-1]?.letterSpacing)??-1.5).toFixed(1)}px</em><input type="range" min="-6" max="6" step=".5" value={(activeText===0?current.textLetterSpacing:current.extraTexts?.[activeText-1]?.letterSpacing)??-1.5} onChange={(e)=>updatePointTypography(Number(e.target.value),undefined)}/></label><small>글자 폭을 줄이면 더 세로로 길고 좁게 보입니다.</small></div>}{activeText>0&&<button className="single-save" style={{marginBottom:10,color:"#a23528"}} onClick={removeText}>선택 문구 삭제</button>}
            {active===0?<div className="photo-slots"><span>사진</span><div className="segmented"><button className="on" onClick={()=>setActiveImage(0)}>표지 사진</button></div></div>:<div className="photo-slots"><span>사진 레이아웃</span><div className="segmented layout-choice"><button className={(current.photoLayout!=="split"&&!current.image2)?"on":""} onClick={()=>setPhotoLayout("single")}>사진 1장</button><button className={(current.photoLayout==="split"||!!current.image2)?"on":""} onClick={()=>setPhotoLayout("split")}>사진 2장</button></div>{(current.photoLayout==="split"||current.image2)&&<><div className="slot-uploads"><label className={activeImage===0?"active":""}>위 칸에 사진 넣기<input type="file" accept="image/*" onChange={(event)=>addSlotPhoto(event,0)}/></label><label className={activeImage===1?"active":""}>아래 칸에 사진 넣기<input type="file" accept="image/*" onChange={(event)=>addSlotPhoto(event,1)}/></label></div><small className="slot-help">문구 박스나 사진을 미리보기에서 바로 드래그해 이동하세요.</small>{current.image2&&<button className="remove-second" onClick={removeSecondPhoto}>두 번째 사진 제거</button>}</>}</div>}
            <div className="overlay-control"><span>작은 이미지</span>{current.overlayImage?<><label>크기 <em>{Math.round((current.overlayWidth||360)/3.6)}%</em><input type="range" min="160" max="720" step="10" value={current.overlayWidth||360} onChange={(event)=>updateCard({overlayWidth:Number(event.target.value)})}/></label><button className="remove-second" onClick={removeOverlayImage}>작은 이미지 제거</button></>:<label className="overlay-upload">＋ 작은 이미지 추가<input type="file" accept="image/*" onChange={addOverlayImage}/></label>}<small>추가한 이미지는 미리보기에서 바로 끌어 이동할 수 있어요.</small></div>
            <label>사진 {activeImage+1} 크기 <em style={{float:"right",fontStyle:"normal",fontWeight:400}}>{Math.round((activeImage===0?(current.imageScale||1):(current.image2Scale||1))*100)}%</em><input type="range" min="1" max="2.5" step="0.05" value={activeImage===0?(current.imageScale||1):(current.image2Scale||1)} onChange={(e) => activeImage===0?updateCard({imageScale:Number(e.target.value)}):updateCard({image2Scale:Number(e.target.value)})}/></label>
            <div className="page-actions single"><button className="danger" onClick={removePage} disabled={cards.length<=1}>현재 페이지 삭제</button></div>
            <button className="single-save" style={{marginBottom:8}} onClick={() => updateCard({imageScale:1,imageX:0,imageY:0,image2Scale:1,image2X:0,image2Y:0,overlayWidth:360,overlayX:760,overlayY:1030,textX:undefined,textY:undefined})}>위치·크기 초기화</button>
            <button className="single-save" onClick={() => saveCard()}>현재 카드 PNG 저장 ↓</button><p className="photo-status">사진 {photoCount}장 · 카드 {cards.length}장 · 사진 1은 선택한 페이지부터 순서대로 배치됩니다.</p></div></div>
        <div className="filmstrip" aria-label="페이지 순서 변경" onDragOver={(event)=>event.preventDefault()} onDrop={(event)=>{event.preventDefault();if(draggedPage.current!==null&&dropPreview){if(dropPreview.index===cards.length)dropPage(draggedPage.current,cards.length-1,"after");else dropPage(draggedPage.current,dropPreview.index,dropPreview.side)}draggedPage.current=null}}>{cards.map((c, i) => <button key={i} draggable className={`${active===i?"active":""} ${dropPreview?.index===i?`drop-${dropPreview.side}`:""}`} title="누른 채 좌우로 끌어 순서 변경" aria-label={`${i+1}페이지 선택 및 순서 변경`} onClick={() => {setActive(i);setActiveText(0);setActiveImage(0)}} onDragStart={(event)=>{draggedPage.current=i;setDropPreview(null);event.currentTarget.classList.add("dragging");event.dataTransfer.effectAllowed="move";event.dataTransfer.setData("text/plain",String(i))}} onDragOver={(event)=>{event.preventDefault();event.dataTransfer.dropEffect="move";const rect=event.currentTarget.getBoundingClientRect();setDropPreview({index:i,side:event.clientX<rect.left+rect.width/2?"before":"after"})}} onDrop={(event)=>{event.preventDefault();event.stopPropagation();const rect=event.currentTarget.getBoundingClientRect();const side=event.clientX<rect.left+rect.width/2?"before":"after";if(draggedPage.current!==null)dropPage(draggedPage.current,i,side);draggedPage.current=null}} onDragEnd={(event)=>{event.currentTarget.classList.remove("dragging");draggedPage.current=null;setDropPreview(null)}}><span style={c.image ? {backgroundImage:`url(${c.image})`} : undefined}>{!c.image && "+"}</span><b>{i + 1}</b></button>)}<button className={`add-page ${dropPreview?.index===cards.length?"drop-before":""}`} onClick={addPage} onDragOver={(event)=>{event.preventDefault();setDropPreview({index:cards.length,side:"before"})}} onDrop={(event)=>{event.preventDefault();event.stopPropagation();if(draggedPage.current!==null)dropPage(draggedPage.current,cards.length-1,"after");draggedPage.current=null}} aria-label="새 페이지 추가" title="새 페이지 추가"><span>＋</span></button><small>썸네일을 누른 채 끌어서 순서를 바꿀 수 있어요.</small></div></section></section></main>;
}
function CardCanvas({ card, index, activeImage, onSelectImage, onSelectText, onChange, onMoveText }: { card: Card; index: number; activeImage:0|1; onSelectImage:(slot:0|1)=>void; onSelectText:(textIndex:number)=>void; onChange: (patch: Partial<Card>) => void; onMoveText:(textIndex:number,x:number,y:number)=>void }) {
  const ref = useRef<HTMLCanvasElement>(null);
  const drag = useRef<{kind:"image"|"text"|"overlay";x:number;y:number;imageX:number;imageY:number;textX:number;textY:number;slot:0|1;textIndex:number}|null>(null);
  useEffect(() => { if (ref.current) renderCard(ref.current, card, index); }, [card, index]);
  function point(event: ReactPointerEvent<HTMLCanvasElement>) { const rect = event.currentTarget.getBoundingClientRect(); return {x:(event.clientX-rect.left)*1080/rect.width,y:(event.clientY-rect.top)*1350/rect.height}; }
  function down(event:ReactPointerEvent<HTMLCanvasElement>){
    event.currentTarget.setPointerCapture(event.pointerId);const p=point(event);const ctx=event.currentTarget.getContext("2d");
    const textIndex=ctx?findTextAt(ctx,card,index,p.x,p.y):null;
    if(textIndex!==null){onSelectText(textIndex);const d=textIndex===0?defaultTextPosition(card,index):(card.extraTexts?.[textIndex-1]||{x:540,y:675});drag.current={kind:"text",...p,slot:activeImage,imageX:0,imageY:0,textIndex,textX:textIndex===0?(card.textX??d.x):d.x,textY:textIndex===0?(card.textY??d.y):d.y};return}
    if(overlayBounds(card)&&pointInBounds(p,overlayBounds(card)!)){drag.current={kind:"overlay",...p,slot:activeImage,imageX:card.overlayX??760,imageY:card.overlayY??1030,textIndex:0,textX:0,textY:0};return}
    const split=index>0&&(card.photoLayout==="split"||Boolean(card.image2));const slot:0|1=split&&p.y>=675?1:0;if(slot!==activeImage)onSelectImage(slot);drag.current={kind:"image",...p,slot,imageX:slot===0?(card.imageX||0):(card.image2X||0),imageY:slot===0?(card.imageY||0):(card.image2Y||0),textIndex:0,textX:0,textY:0};
  }
  function move(event:ReactPointerEvent<HTMLCanvasElement>){if(!drag.current)return;const p=point(event);const dx=p.x-drag.current.x,dy=p.y-drag.current.y;if(drag.current.kind==="overlay")onChange({overlayX:drag.current.imageX+dx,overlayY:drag.current.imageY+dy});else if(drag.current.kind==="image"){if(drag.current.slot===0)onChange({imageX:drag.current.imageX+dx,imageY:drag.current.imageY+dy});else onChange({image2X:drag.current.imageX+dx,image2Y:drag.current.imageY+dy});}else onMoveText(drag.current.textIndex,drag.current.textX+dx,drag.current.textY+dy);}
  function up(){drag.current=null;}
  return <canvas ref={ref} width={1080} height={1350} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} style={{width:"min(100%, 430px)",height:"auto",display:"block",boxShadow:"0 18px 38px #28251d32",cursor:"grab",touchAction:"none"}} aria-label={`${index + 1}번째 카드 미리보기`}/>;
}
async function renderCard(canvas: HTMLCanvasElement, card: Card, index: number) {
  await Promise.all([document.fonts.load("600 38px Pretendard"),document.fonts.load("800 84px Pretendard"),document.fonts.load('400 42px "IBM Plex Sans KR"')]);
  canvas.width = 1080; canvas.height = 1350; const ctx = canvas.getContext("2d"); if (!ctx) return; ctx.clearRect(0, 0, 1080, 1350); ctx.fillStyle = "#d2cec6"; ctx.fillRect(0, 0, 1080, 1350);
  const split=index>0&&(card.photoLayout==="split"||Boolean(card.image2));
  if(split){if(card.image)await drawImageCover(ctx,card.image,0,0,1080,677,card.imageScale||1,card.imageX||0,card.imageY||0);else drawEmptySlot(ctx,0,677,"위 사진을 추가하세요");if(card.image2)await drawImageCover(ctx,card.image2,0,673,1080,677,card.image2Scale||1,card.image2X||0,card.image2Y||0);else drawEmptySlot(ctx,673,677,"아래 사진을 추가하세요");}
  else if (card.image) await drawImageCover(ctx,card.image,0,0,1080,1350,card.imageScale||1,card.imageX||0,card.imageY||0);
  else drawEmptySlot(ctx,0,1350,"사진을 추가하세요",true);
  if(card.overlayImage)await drawOverlayImage(ctx,card);
  if (index === 0) { const grad = ctx.createLinearGradient(0, 540, 0, 1350); grad.addColorStop(0, "transparent"); grad.addColorStop(1, "rgba(0,0,0,.94)"); ctx.fillStyle = grad; ctx.fillRect(0, 0, 1080, 1350); const p=defaultTextPosition(card,index); if(card.textStyle==="point")drawTextBox(ctx,card.text,card.textX??p.x,card.textY??p.y,"point",card.textLetterSpacing,card.textWidthScale);else{const coverFont="800 84px Pretendard"; const lines = wrap(ctx, card.text, 880, coverFont); const centerX=Math.max(440,Math.min(640,card.textX??p.x)),centerY=card.textY??p.y; ctx.fillStyle = "white"; ctx.font = coverFont; ctx.textAlign="center"; ctx.shadowColor="rgba(0,0,0,.38)";ctx.shadowBlur=10;ctx.shadowOffsetX=0;ctx.shadowOffsetY=3; const lineHeight=106,blockH=lines.length*lineHeight; const firstBaseline=centerY-blockH/2+84; lines.forEach((line, i) => ctx.fillText(line, centerX, firstBaseline + i * lineHeight)); ctx.shadowColor="transparent";ctx.shadowBlur=0;ctx.shadowOffsetX=0;ctx.shadowOffsetY=0;ctx.textAlign="left";} (card.extraTexts||[]).forEach((block)=>drawTextBox(ctx,block.text,block.x,block.y,block.style,block.letterSpacing,block.widthScale)); return; }
  const p=defaultTextPosition(card,index); drawTextBox(ctx,card.text,card.textX??p.x,card.textY??p.y,card.textStyle,card.textLetterSpacing,card.textWidthScale); (card.extraTexts||[]).forEach((block)=>drawTextBox(ctx,block.text,block.x,block.y,block.style,block.letterSpacing,block.widthScale));
}
function drawEmptySlot(ctx:CanvasRenderingContext2D,y:number,height:number,label:string,showSize=false){ctx.fillStyle="#d2cec6";ctx.fillRect(0,y,1080,height);ctx.fillStyle="#706c65";ctx.textAlign="center";ctx.font="700 42px Pretendard";ctx.fillText(label,540,y+height/2-(showSize?15:0));if(showSize){ctx.font="400 30px Pretendard";ctx.fillText("권장 1080 × 1350",540,y+height/2+40);}ctx.textAlign="left";}
async function drawImageCover(ctx:CanvasRenderingContext2D,src:string,x:number,y:number,width:number,height:number,zoom:number,offsetX:number,offsetY:number){const img=new Image();img.src=src;try{await img.decode();const scale=Math.max(width/img.width,height/img.height)*zoom;const drawW=img.width*scale,drawH=img.height*scale;ctx.save();ctx.beginPath();ctx.rect(x,y,width,height);ctx.clip();ctx.drawImage(img,x+(width-drawW)/2+offsetX,y+(height-drawH)/2+offsetY,drawW,drawH);ctx.restore();}catch{}}
function overlayBounds(card:Card){if(!card.overlayImage)return null;const width=card.overlayWidth??360,height=width/(card.overlayAspect||4/3),centerX=card.overlayX??760,centerY=card.overlayY??1030;return{x:centerX-width/2,y:centerY-height/2,width,height}}
function pointInBounds(point:{x:number;y:number},bounds:{x:number;y:number;width:number;height:number}){return point.x>=bounds.x&&point.x<=bounds.x+bounds.width&&point.y>=bounds.y&&point.y<=bounds.y+bounds.height}
async function drawOverlayImage(ctx:CanvasRenderingContext2D,card:Card){const bounds=overlayBounds(card);if(!bounds||!card.overlayImage)return;const img=new Image();img.src=card.overlayImage;try{await img.decode();ctx.save();ctx.shadowColor="rgba(0,0,0,.18)";ctx.shadowBlur=14;ctx.shadowOffsetY=5;ctx.drawImage(img,bounds.x,bounds.y,bounds.width,bounds.height);ctx.restore()}catch{}}
function textBoxBounds(ctx:CanvasRenderingContext2D,text:string,centerX:number,centerY:number,style:TextStyle="default",letterSpacing?:number,widthScale?:number){const point=style==="point",font=point?'400 42px "IBM Plex Sans KR"':"600 38px Pretendard",lineHeight=point?57:54,padX=38,padY=point?28:30,spacing=point?(letterSpacing??-1.5):0,scale=point?(widthScale??0.86):1;ctx.letterSpacing=`${spacing}px`;const lines=wrap(ctx,text,760/scale,font);ctx.font=font;const widest=Math.max(...lines.map((line)=>ctx.measureText(line).width))*scale;const width=Math.min(836,Math.max(360,Math.ceil(widest+padX*2))),height=lines.length*lineHeight+padY*2;const x=Math.max(18,Math.min(1080-width-18,centerX-width/2)),y=Math.max(18,Math.min(1350-height-18,centerY-height/2));return{x,y,width,height,lines,font,lineHeight,padX,padY,point,spacing,scale}}
function drawTextBox(ctx:CanvasRenderingContext2D,text:string,centerX:number,centerY:number,style:TextStyle="default",letterSpacing?:number,widthScale?:number){const box=textBoxBounds(ctx,text,centerX,centerY,style,letterSpacing,widthScale);ctx.font=box.font;ctx.letterSpacing=`${box.spacing}px`;ctx.fillStyle=box.point?"#feb249":"white";ctx.fillRect(box.x,box.y,box.width,box.height);ctx.strokeStyle="#111";ctx.lineWidth=3;ctx.strokeRect(box.x,box.y,box.width,box.height);ctx.fillStyle="#111";ctx.textBaseline="middle";box.lines.forEach((line,i)=>{ctx.save();ctx.translate(box.x+box.padX,box.y+box.padY+box.lineHeight/2+i*box.lineHeight);ctx.scale(box.scale,1);ctx.fillText(line,0,0);ctx.restore()});ctx.textBaseline="alphabetic";ctx.letterSpacing="0px";}
function findTextAt(ctx:CanvasRenderingContext2D,card:Card,index:number,x:number,y:number){const areas:{index:number;x:number;y:number;width:number;height:number}[]=[];if(index===0&&card.textStyle!=="point"){const font="800 84px Pretendard",lineHeight=106,lines=wrap(ctx,card.text,880,font),p=defaultTextPosition(card,index),centerX=Math.max(440,Math.min(640,card.textX??p.x)),centerY=card.textY??p.y;ctx.font=font;const width=Math.min(920,Math.max(240,Math.max(...lines.map((line)=>ctx.measureText(line).width))+40)),height=lines.length*lineHeight;areas.push({index:0,x:centerX-width/2,y:centerY-height/2,width,height})}else{const p=defaultTextPosition(card,index),box=textBoxBounds(ctx,card.text,card.textX??p.x,card.textY??p.y,card.textStyle,card.textLetterSpacing,card.textWidthScale);areas.push({index:0,x:box.x,y:box.y,width:box.width,height:box.height})}(card.extraTexts||[]).forEach((item,i)=>{const box=textBoxBounds(ctx,item.text,item.x,item.y,item.style,item.letterSpacing,item.widthScale);areas.push({index:i+1,x:box.x,y:box.y,width:box.width,height:box.height})});ctx.letterSpacing="0px";for(let i=areas.length-1;i>=0;i--){const area=areas[i];if(x>=area.x&&x<=area.x+area.width&&y>=area.y&&y<=area.y+area.height)return area.index}return null}
function defaultTextPosition(card:Card,index:number){if(index===0)return{x:540,y:1090};if(card.layout==="top")return{x:470,y:190};if(card.layout==="center")return{x:540,y:675};return{x:470,y:1135};}
function wrap(ctx: CanvasRenderingContext2D, text: string, maxWidth: number, font: string) { ctx.font = font; const lines: string[] = []; const paragraphs=text.replace(/\r\n?/g,"\n").split("\n"); for(const paragraph of paragraphs){if(!paragraph.trim()){lines.push("");continue;}const words=paragraph.trim().split(/\s+/);let line="";for(const word of words){const test=line?`${line} ${word}`:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word;}else line=test;}if(line)lines.push(line);}return lines.length?lines:[""]; }
